---
title: "p8105_hw6_yc4195.Rmd"
author: "Yimin Chen"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(modelr)
library(ggplot2)
library(dplyr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE, 
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 2


```{r}
homicide_df = 
  read_csv(file = "data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    victim_age = as.numeric(victim_age),
    victim_race = fct(victim_race),
    resolution = ifelse(disposition == "Closed by arrest", 1, 0)) %>% 
  group_by(city_state)%>% 
  filter(city_state != "Tulsa,AL"&city_state!="Dallas,TX" & city_state!="Phoenix,AZ" & city_state!="Kansas City,MO")%>% 
  filter(victim_race=="White" | victim_race=="Black") %>%
  select(city_state, resolution, victim_age, victim_race, victim_sex)
```

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "Baltimore,MD")%>% 
  glm(resolution ~ victim_age + victim_sex + victim_race, data = ., family =binomial())%>%
  broom::tidy() %>%
  mutate(
    OR = exp(estimate),
    lower_ci = exp(estimate - 1.96 * std.error),
    upper_ci = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, estimate, OR, lower_ci,upper_ci ) %>% 
  knitr::kable(digits = 3)
baltimore_df
```

```{r}
homicide_or = 
  homicide_df %>% 
  nest(data = -city_state) %>% 
  mutate(
    regression = map(.x = data, ~glm(formula = resolution ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
    results = map(regression, broom::tidy)
  ) %>% 
  select(-data, -regression) %>% 
  unnest(results) %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(
    OR = exp(estimate),
    lower_ci = exp(estimate - 1.96 * std.error),
    upper_ci = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state,OR, lower_ci,upper_ci ) 
homicide_or
```


```{r}
homicide_or %>% 
  ggplot(aes(x = fct_reorder(city_state, OR), y = OR)) +
  geom_point() + 
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(
    x = "Name for City and State",
    y = "Adjusted Odd Ratio",
    title = "Estimated ORs and CIs for each city"
  )

```


## Problem 3

```{r}
birthweight_df = 
  read_csv("data/birthweight.csv")
skimr::skim(birthweight_df)
birthweight_df %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = case_when(
      babysex == 1 ~ "Male",
      babysex == 2 ~ "Female"
    ))%>% 
      mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace),
    parity = as.factor(parity),
    pnumlbw = as.factor(pnumlbw),
    pnumsga = as.factor(pnumsga)) 
```
WE first check that there are no missing data in the birthweight dataset, then we clean the data for regression analysis such as converting numeric to factor where appropriate.The dataset contains `r nrow(birthweight_df)` rows and `r ncol(birthweight_df)` columns in total.


```{r}
multi_model = lm(bwt ~ ., data = birthweight_df)
multi_model %>% 
  broom::tidy() %>% 
  knitr::kable()
step(multi_model, direction = 'both')
multi_model1 = lm(bwt ~ babysex + bhead + blength + delwt + fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = birthweight_df)
multi_model1 %>% 
  broom::tidy() %>% 
  knitr::kable()
```

```{r residual_plot}
birthweight_df %>% 
  modelr::add_residuals(multi_model1) %>%
  modelr::add_predictions(multi_model1) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point(alpha = 0.3) +
  labs(
    title = "Predicted Values versus Residuals of the Model",
    x = "Predicted values",
    y = "Residuals"
    ) +
  theme(plot.title = element_text(hjust = 0.5))+
  geom_line(aes(y = 0), color = "blue")
```


```{r model1}
model1 = lm(bwt ~ blength + gaweeks, data = birthweight_df)
model1 %>% 
  broom::tidy() %>% 
  knitr::kable()
```


```{r model2}
model2 = lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = birthweight_df)
model2 %>% 
  broom::tidy() %>% 
  knitr::kable()
```

### Cross Validaton

```{r cv}
cv_df = 
  crossv_mc(birthweight_df, 100)

cv_df = 
  cv_df %>%
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) %>% 
  mutate(
    model11 = map(.x = train, ~lm(bwt ~ blength + gaweeks, data = birthweight_df)),
    model22 = map(.x = train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + blength*babysex + bhead*babysex + bhead*blength*babysex, data = birthweight_df)),
    bestmodel = map(.x = train, ~lm(bwt ~ fincome + frace + parity + mrace + babysex + mheight+ ppwt+ gaweeks + smoken + wtgain + blength + bhead, data = birthweight_df))
  ) %>% 
  mutate(
    rmse_model1 = map2_dbl(.x = model11, .y = test, ~rmse(model = .x, data =.y)),
    rmse_model2 = map2_dbl(.x = model22, .y = test, ~rmse(model = .x, data =.y)),
    rmse_bestmodel = map2_dbl(.x = bestmodel, .y = test, ~rmse(model = .x, data =.y))
  )
```

### Violin plot

```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse,color = model)) + 
  geom_violin() +
  geom_boxplot(alpha = 0.5, color = "blue")+
  labs(
    x = "Models",
    y = "RMSE",
    title = "Distribution of 3 models' RMSE"
  )+
  theme( plot.title = element_text(hjust = .5))
  
```